### ISSUE TITLE
Grant access to Bitwarded stored EOA address for minting Wildhorn V2 NFTs

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-community#129]
@SCBuergel See #128, pretty much we will need to grant access to an EOA for minting to simplify the transaction generation process.

**Comment by QYuQianchen** [comment]
We can use the same address that minted `HODLr` tokens for this time. That address has been stored in Bitwarden.

**Comment by jjperezaguinaga** [comment]
@QYuQianchen what's the name of that address? Would be worth separating it from the rest of the tech group passwords.

**Comment by jjperezaguinaga** [comment]
EOA granted minting rights on https://blockscout.com/xdai/mainnet/tx/0x167221cb51d784a4b89029367c12b523a40a677a80c126702904031c527d5960.
