### ISSUE TITLE
Execute the script to mint the `4` categories Wildhorn V2 NFTs based on Dune info

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-community#131]
Please document all the commands and steps in https://github.com/hoprnet/hopr-stake.

**Comment by QYuQianchen** [comment]
Follow instructions in README after https://github.com/hoprnet/hopr-stake/pull/28 is merged.

**Comment by jjperezaguinaga** [comment]
Already completed, all mints had been minted.
