### ISSUE TITLE
General application improvements

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-community#49]
![HOPR_Staking_UI_Feedback 2](https://user-images.githubusercontent.com/1128312/126996735-502744d2-2e16-4a24-ab9a-590bb20ec637.jpg)

- [x] #70
- [x] #71
- [x] #72
- [x] #73
- [ ] #74

Additional tasks:

- [x] #85
- [ ] #84
- [ ] #83
- [x] #82
- [ ] #81
- [ ] #80

Additional bugs:

- [x] #86
- [x] #87
- [ ] #88
- [ ] #93
- [ ] Ignored label is also added on the non-locked NFTs 

UI improvements:
- [ ] #89
- [ ] #91
- [ ] #92

**Comment by jjperezaguinaga** [comment]
Adding additional tasks:

- [ ] Showcase the amount of virtual locked for investors
- [ ] Provide feedback on ignoring locking NFTs that are not over 10%
- [ ] Ignore APR from multiple NFTs and show only the biggest
- [ ] Provide feedback on rejected transactions so UI doesn't block
- [ ] Provide feedback when the user is in a non-supported chain.
