### ISSUE TITLE
Gather the addresses of all existing participants of the staking contract program (via TheGraph) up to Aug 6th 12:00 pm

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-community#95]

**Comment by QYuQianchen** [comment]
Query here: https://dune.xyz/queries/109219
Result here: [staking_accounts.csv](https://github.com/hoprnet/hopr-community/files/7006466/staking_accounts.csv)

**Comment by jjperezaguinaga** [comment]
@QYuQianchen thanks!
